[[language]]
name = "python"
scope = "source.python"
roots = []
injection-regex = "python"
file-types = ["py"]
comment-token = "#"
auto-format = true
formatter = { command = "black", args = ["-", "--quiet"] }
language-server = { command = "pyright-langserver", args = ["--stdio"] }
indent = { tab-width = 4, unit = "    " }
config = {}

[[language]]
name = "toml"
scope = "source.toml"
roots = ["*.toml"]
auto-format = true
injection-regex = "toml"
file-types = ["toml"]
comment-token = "#"
language-server = { command = "taplo", args = ["lsp", "stdio"] }
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "markdown"
scope = "text.markdown"
roots = []
auto-format = true
file-types = ["md"]
comment-token = "#"
language-server = { command = "marksman" }

[[language]]
name = "hcl"
scope = "source.hcl"
injection-regex = "(hcl|tf|nomad)"
file-types = ["hcl", "tf", "nomad"]
roots = []
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
language-server = { command = "terraform-ls", args = [
  "serve",
], language-id = "terraform" }
auto-format = true

[[language]]
name = "tfvars"
scope = "source.tfvars"
file-types = ["tfvars"]
roots = []
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
language-server = { command = "terraform-ls", args = [
  "serve",
], language-id = "terraform-vars" }
auto-format = true
grammar = "hcl"
